apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathematics-deployment
  labels:
    app: mathematics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mathematics-app
  template:
    metadata:
      labels:
        app: mathematics-app
    spec:
      containers:
      - name: mathematics
        image: djmartinez.io/mathematics:1.0
        ports:
        - containerPort: 5000