apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |
    { 
      "externalServices": {
        "mathematics": {
            "url": "http://mathematics-service:5000",
            "endpoints": {
              "random": "/api/v1/random"
            }
          }
        }
    }