kind: Service
apiVersion: v1
metadata:
  namespace: djmartinez-io
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80