kind: Service
apiVersion: v1
metadata:
  name: djmartinez-service
spec:
  type: LoadBalancer
  selector:
    app: djmartinez-app
  ports:
  - name: frontend 
    protocol: TCP
    port: 80
    targetPort: 80
  - name: mathematics
    protocol: TCP
    port: 5000
    targetPort: 5000